#!/usr/bin/env lua
local filename = ...
local f = io.open(filename, 'r')

local r = f:read '*a'

f:close()

local command = './main'
local tot = ''

for i, v in r:gmatch("(%d+) (%d+)") do

	local s = command .. ' ' .. i .. ' ' .. v .. ' ; '
	tot = tot .. s

end

tot = tot:sub(1, -4)

os.execute(tot)